### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by swanseahost** [bbscoin/bbscoin-pool#6]
Hi,

I keep getting this error

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/miner/bbscoin-pool/init.js:19:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
2018-05-16 23:51:42 [master] Pool fork 3 died, spawning replacement worker...

How can I fix please ?

**Comment by randing89** [comment]
Looks like you changed something in `lib/pool.js`. The code is running on main pool just fine.

**Comment by swanseahost** [comment]
Not changed a single thing.

Also get this with the wallet

{"code":-32601,"message":"Method not found"} in the pool admin.html

**Comment by swanseahost** [comment]
started wallet like this ./simplewallet --wallet-file PoolWallet --rpc-bind-ip 127.0.0.1 --rpc-bind-port 8070 --password XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by randing89** [comment]
Pull the latest master.  And you should start walletd not simplewallet

**Comment by swanseahost** [comment]
same command line ?

**Comment by randing89** [comment]
Create a new wallet file with ./walletd -w NewPoolWallet -g

**Comment by swanseahost** [comment]
Where do I put the password ?

**Comment by swanseahost** [comment]
2018-May-18 01:01:29.695504 WARNING [109.126.140.60:3539 INC] Exception in connectionHandler: TcpConnection::read
2018-May-18 01:01:30.023982 WARNING [184.22.90.122:60612 INC] Exception in connectionHandler: TcpConnection::read
2018-May-18 01:01:30.416472 WARNING [134.236.36.128:53174 INC] Exception in connectionHandler: TcpConnection::read
2018-May-18 01:01:59.185748 WARNING Failed to validate block 3f1d7f6557c2928ae15188ffe6961e7d8a2206c6cfdd8e907f4f53337a6253f5: Wrong block version
2018-May-18 01:02:08.925357 WARNING Failed to validate block 3f1d7f6557c2928ae15188ffe6961e7d8a2206c6cfdd8e907f4f53337a6253f5: Wrong block version
2018-May-18 01:02:12.275184 WARNING Failed to validate block 3f1d7f6557c2928ae15188ffe6961e7d8a2206c6cfdd8e907f4f53337a6253f5: Wrong block version
2018-May-18 01:02:22.889160 WARNING Failed to validate block 3f1d7f6557c2928ae15188ffe6961e7d8a2206c6cfdd8e907f4f53337a6253f5: Wrong block version
2018-May-18 01:02:35.618761 WARNING Failed to validate block 3f1d7f6557c2928ae15188ffe6961e7d8a2206c6cfdd8e907f4f53337a6253f5: Wrong block version
2018-May-18 01:02:44.815210 WARNING Failed to validate block 3f1d7f6557c2928ae15188ffe6961e7d8a2206c6cfdd8e907f4f53337a6253f5: Wrong block version
2018-May-18 01:02:47.915145 WARNING Failed to validate block 3f1d7f6557c2928ae15188ffe6961e7d8a2206c6cfdd8e907f4f53337a6253f5: Wrong block version
